/* eslint-disable */
/**
 * Generated API - Run `npx convex dev` to regenerate
 */

// Placeholder exports - regenerated by `npx convex dev`
export const api = {
  tools: {
    list: "tools:list",
    get: "tools:get",
    findForTask: "tools:findForTask",
    create: "tools:create",
    toggle: "tools:toggle",
    recordUsage: "tools:recordUsage",
    getUsageStats: "tools:getUsageStats",
    seedBuiltins: "tools:seedBuiltins",
  },
};

export const internal = {};
