/* eslint-disable */
/**
 * Generated API types - Run `npx convex dev` to regenerate
 */

import type { GenericId } from "convex/values";

export type Id<T extends string> = GenericId<T>;

// API placeholder - regenerated by `npx convex dev`
export declare const api: {
  tools: {
    list: any;
    get: any;
    findForTask: any;
    create: any;
    toggle: any;
    recordUsage: any;
    getUsageStats: any;
    seedBuiltins: any;
  };
};

export declare const internal: any;
